/** Implementation boundary specification. No production adapter is shipped. */
export type ThreadRef = { hostId: string; threadId: string };
export type Capabilities = { inventory: boolean; atomicBatch: boolean; trustedApproval: boolean; knownEffects: boolean; reconciliation: boolean; restore: boolean; cancellation: boolean; contextConsumption: boolean };
export interface Claim { claimId: string; section: 'goal'|'decisions'|'constraints'|'changes'|'validation'|'failures'|'unresolved'|'nextActions'; text: string; kind: 'observation'|'inference'; evidenceRefs: {threadRef: ThreadRef; turnId: string; artifactRef?: string}[]; applicability: {projectId: string; branch: string; version: string}; topic?: string }
export interface Thread { ref: ThreadRef; projectId: string; stateRevision: number; runRefs: string[]; claims: Claim[]; sourceText: string; readable: boolean; managed: boolean; referencesComplete: boolean; effectsKnown: boolean; effectRefs: ThreadRef[]; activeTurn: boolean; lease: boolean; pending: boolean; preserved: boolean; unmerged: boolean; archived: boolean; hubArchived: boolean; archiveOwner?: string|null; representative: boolean }
export interface Inventory { schemaVersion: 1; createdAt: number; hostId: string; canonicalProjectId: string; canonicalProjectPath: string; branch: string; runId: string; hubRevision: number; completeness: 'complete'|'partial'|'unknown'; runs: {runId: string; status: string; pending: boolean}[]; threads: Thread[] }
export interface Effect { threadRef: ThreadRef; expectedRevision: number; beforeArchived: boolean; archivedRevision?: number; sourceDigest?: string }
export interface Plan { schemaVersion: 1; createdAt: number; planId: string; revision: number; kind: 'archive'|'restore'; digest: string; scopeDigest: string; snapshotId: string; operationId?: string; effects: Effect[]; expiresAt: number; recordId: string; recordRevision: number; recordDigest: string; status: 'draft'|'ready_for_review'; blockers: string[] }
export interface Reservation { token: string; fence: number; operationId: string; planDigest: string; expiresAt: number }
export interface ItemResult { threadRef: ThreadRef; status: string; changed: boolean; beforeArchived?: boolean; afterArchived?: boolean; afterRevision?: number; ownerOperationId?: string }
export interface HubResult { schemaVersion: 1; createdAt: number; operationId: string; planDigest: string; itemResults: ItemResult[]; cancelled?: boolean }
export interface HubAdapter { readonly mode: 'fixture'|'production'; readonly capabilities: Capabilities; inspect(): Inventory; requireMutation(): void; reserve(plan: Plan, snapshot: Inventory, operationId: string): Reservation; apply(reservation: Reservation, plan: Plan, snapshot: Inventory, operationId: string, verifyApproval: () => boolean): HubResult; readOperation(operationId: string): HubResult|null; cancelOperation?(plan: Plan, operationId: string): HubResult }
export interface ApprovalReceipt { schemaVersion: 1; createdAt: number; receiptId: string; issuer: string; mode: 'fixture'|'production'; actorRef: string; operationKind: 'archive'|'restore'; planDigest: string; approvedEffects: Effect[]; expiresAt: number; signature: string }
export interface ApprovalVerifier { verify(receipt: ApprovalReceipt, plan: Plan, now: number): boolean }
export interface GraphAdapter { readPublished(snapshot: Inventory, now: number): { status: 'unavailable'|'stale'|'published'; mode: string; revision?: string; observedAt?: number; edges: unknown[]; authority?: false } }
